[package]
name = "tmt"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-macro = "0.3.31"
rand = "0.8.5"
reqwest = "0.12.8"
tokio = { version = "1.40.0", features = ["full"] }
twitch_api = { version = "0.7.0-rc.8", features = ["all", "reqwest"] }
